#!/bin/sh

. "$HOME/scripts/scripts-config"

if [ ! -d $BACKUP_DIR ]
then
    echo "Backup directory not found"
    exit 1
fi

echo "Backing up into $BACKUP_DIR"

rsync -avEh --progress --delete "$FILES_DIR" "$BACKUP_DIR"
