#!/bin/sh

FILES_DIR="$HOME/files"

BACKUP_DIR="/media/$USER/Maxtor/backup"

if [ ! -d $BACKUP_DIR ]
then
    echo "Backup directory not found"
    exit 1
fi

rsync -avEh --progress --delete "$FILES_DIR" "$BACKUP_DIR"
