#!/bin/sh

if [ -z "$BACKUP_DIR" ]; then
    echo "BACKUP_DIR is not set"
    exit 1
fi

if [ -z "$FILES_DIR" ]; then
    echo "FILES_DIR is not set"
    exit 1
fi

if [ ! -d "$BACKUP_DIR" ]
then
    echo "Backup directory not found"
    exit 1
fi

echo "Backing up into $BACKUP_DIR"

rsync -avEh --progress --delete "$FILES_DIR" "$BACKUP_DIR"

