#!/bin/sh

echo "scripts: $SCRIPTS_DIR"

youtube_dl_path="$SCRIPTS_DIR/youtube-dl"

if [ ! -e "$youtube_dl_path" ]
then
    curl -L https://yt-dl.org/downloads/latest/youtube-dl -o "$youtube_dl_path"
    chmod a+rx "$youtube_dl_path"
fi

cd $MUSIC_DIR
youtube-dl --extract-audio --audio-format mp3 "$1"

