#!/bin/sh

. "$HOME/scripts/scripts-config"

if [ ! -d "$SUCKLESS_DIR/$1" ]
then
    git clone "https://github.com/carlocamurri/$1.git" "$SUCKLESS_DIR/$1"
else
    echo "$1 already present at $SUCKLESS_DIR/$1"
fi
