#!/bin/sh

if [ -z "$1" ]
then
    echo "No Python version specified"
    exit 1
fi

PYTHON_VERSION=$1

FTP_URL="https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz"

PYTHON_DL_DIR="Python-$PYTHON_VERSION"

curl -L $FTP_URL -o $PYTHON_DL_DIR.tgz || exit 1
tar -zxvf $PYTHON_DL_DIR.tgz || exit 1

cd $PYTHON_DL_DIR
make clean
./configure --prefix=$HOME/.local
make
make install

cd ..
rm $PYTHON_DL_DIR.tgz
rm -rf $PYTHON_DL_DIR

