#!/bin/sh

SUCKLESS_DIRNAME="suckless"

SUCKLESS_DIR="$HOME/$SUCKLESS_DIRNAME"

if [ ! -d "$SUCKLESS_DIR" ]
then
    mkdir "$SUCKLESS_DIR"
fi

cd "$SUCKLESS_DIR"

git clone https://git.suckless.org/dwm

cd dwm || exit 1
make clean install || exit 1
