#!/bin/sh

# Useful
apt-get install curl -y

# Python ssl
apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev -y

# Music conversion to mp3
apt-get install ffmpeg -y

# Get sensor data
apt-get install lm-sensors -y

# System performance
apt-get install htop -y

# Lint shell scripts
apt-get install shellcheck -y

# VIM
apt-get install vim -y

# Suckless stuff 
apt-get install libx11-dev libxft-dev libxinerama-dev -y

