#!/bin/sh

. "$HOME/scripts/scripts-config"

if [ ! -e $BACKUP_FILES_DIR ]
then
    echo "Backup directory not found: $BACKUP_FILES_DIR"
    exit 1
fi

if  [ -e $FILES_DIR ]
then
    echo "Restore location found: $FILES_DIR, overwriting..."
    rm -rf $FILES_DIR
fi

echo "Restoring backup from $BACKUP_FILES_DIR into $FILES_DIR ..."

cp -r $BACKUP_FILES_DIR $FILES_DIR
