#!/bin/sh

JAVA_DIR="$HOME/.local/java"

JDK_DIRNAME=$(echo "$1" | sed "s/\.tar\.gz//")

if [ ! -d "$JAVA_DIR" ]
then
    mkdir "$JAVA_DIR"
fi

mv "$1" "$JAVA_DIR"
cd "$JAVA_DIR"

JDK_DIR="$JAVA_DIR/$JDK_DIRNAME"

if [ -d "$JDK_DIR" ]
then
    rm -rf "$JDK_DIR/*"
else
    mkdir "$JDK_DIR"
fi

tar -xvf "$1" --directory="$JDK_DIR" --strip-components=1

rm "$1"
